osx_image: xcode8.3
dist: trusty
sudo: false
language: node_js
node_js: '8'
os:
- linux
- osx
notifications:
  email: false
addons:
  apt:
    packages:
    - rpm
    - libsecret-1-0
    - libsecret-1-dev
    - libgnome-keyring-dev
before_script: npm update
script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run release-linux; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run release-osx; fi
before_deploy:
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then export version=$(cat package.json | grep
  '"version"' | cut -d '"' -f4); if [[ "$TRAVIS_TAG" == *"-"* ]]; then export deb_distribution=unstable;
  else export deb_distribution=stable; fi; if [[ "$TRAVIS_BRANCH" == "master" ]];
  then export deb_distribution=nightly; fi; export date=$(date +%Y-%m-%d); cp packaging/debian/bintray.json
  bintray.json; sed -i s/'{version}'/$version/g bintray.json; sed -i s/'{date}'/$date/g
  bintray.json; sed -i s/'{deb_distribution}'/$deb_distribution/g bintray.json; fi;
  git tag v$(cat package.json | grep '"version":' | cut -d '"' -f4)
deploy:
  - provider: releases
    file_glob: true
    file: dist/*.deb,dist/*.yml,dist/*.dmg,dist/*.rpm
    skip_cleanup: true
    overwrite: true
    api_key:
      secure: BRt/TM+aZd+uli7tOdO/fddqmnjgcT1psYa9WknVB/BYE8GcZ5D/6zGJdeXv4A1v4+AS6RxzkzVytewAfvL6rXcUDPUy4o5+O21N1c8kuzhZkd+kTOeOTpX+wySAQ+oYcrUEvvNZb82rbRNnjdD+sAfpWZlJYJcjvergDduaXncPKqxerHkRrAulhiO8+9sryt5m+CQPpT2kM6o4VYAclNG6M4u09H7rbpm05TcfuFdqi3ZvRqktdES0IIiu6k4XBJ5osHvO4mX53nKW8b9CMYkcHFrMomIsnq9TOYR4o0IxKIkdDde9jOnQcQjJc4YYo9CHvjUpbU4WneylrJJ3RLMF4v4EC1rhLMAm9aw5jAcSEj5ZiipsMpCqWbyGm8bhzqXnLfTyeeaS6ItovAfcQIlovtED4fKAv0MYKOwFYhY1NKMOFiC2uGL2/+/WT1JKB9V03eqqPWCsOkKOlxsiEJfOBgvhnnAAocegwQOupa8ti/CDq/IRlFoLI5F0BGLp+I6lLccAykt6+zF2nEHFqGw0QYuRHv8ULk630c0azEWNwOwSrbPBYhqwXwMphuoG2QUZCUTon+vjtkCZhF20y7HD4hpTzGQhvSKnkwi9PkrjOv2U/ImdU0luWTrTaP+NiODUgT1JqhtgRqstuhdpil0huTvngfOFuKYegrAOqyA=
    on:
      condition: $TRAVIS_BRANCH == "master"
  - provider: bintray
    file: bintray.json
    user: raffis
    key:
      secure: BWv8xZaOQsptR6/CJdvAOD5e7NmEH3aJ83xWfSrxwK52NN7QmSNYBXhM4gMiRvUJXMYIcu6OJhlo3W86M2YOeHGtmH1biLwFp7NxIMEQUouuMBoezg5jU47M4ydk/ro44du/Krvk6jnXHkgHDsnCknPP5RD/Z+Dd2mgTL+iNbvfvklW3pd0y1q1CiZfyaEvRl8OXUyzERnS7NsayjcGOOi5Ea4VYR87tkmXBguV6XQI0CbN9RJ1VQuipYVYevZzMAO1iHDj66nEJYT0XXBOHPUYsYP/iO4bLvXkbUxXi/WU4dQbAkLFD3jYRl3UCpaUvTBoAPooD9Vh8FCq8rUrXfL0TfJ3+awvct7ltKY+E+FiDuiAdlsj+C0uL8n4Do5MNNqE+e22/XrV/Lfhpu7K65173/p6qkJyo1NanqWQJTmmUs1oSVtU+V1Ze6Ybr3BI4J6H/djGkYiIdfLVocBA24gZGmNsi66YTIJeGfN2O1rGOKk/BsxXhnnvDg6XDAH10/kXzNKakDVRGY0DMCiSUwxkozVre0o3wvkwZfWWh6JcomlxDqbCTVLNijIkkoo1GX394wojoe7s8h9HLVHVOD//bACdq9twNc9jvfJJEVk1icygzK6BQxIY81AU6/iKfxUpJ586HGkQjPs+E/Sq5xExo6bpSOa/Ik5u0K19h/P4=
    on:
      condition: ($TRAVIS_OS_NAME = "linux" && $TRAVIS_BRANCH == "master")
  - provider: bintray
    file: bintray.json
    user: raffis
    key:
      secure: BWv8xZaOQsptR6/CJdvAOD5e7NmEH3aJ83xWfSrxwK52NN7QmSNYBXhM4gMiRvUJXMYIcu6OJhlo3W86M2YOeHGtmH1biLwFp7NxIMEQUouuMBoezg5jU47M4ydk/ro44du/Krvk6jnXHkgHDsnCknPP5RD/Z+Dd2mgTL+iNbvfvklW3pd0y1q1CiZfyaEvRl8OXUyzERnS7NsayjcGOOi5Ea4VYR87tkmXBguV6XQI0CbN9RJ1VQuipYVYevZzMAO1iHDj66nEJYT0XXBOHPUYsYP/iO4bLvXkbUxXi/WU4dQbAkLFD3jYRl3UCpaUvTBoAPooD9Vh8FCq8rUrXfL0TfJ3+awvct7ltKY+E+FiDuiAdlsj+C0uL8n4Do5MNNqE+e22/XrV/Lfhpu7K65173/p6qkJyo1NanqWQJTmmUs1oSVtU+V1Ze6Ybr3BI4J6H/djGkYiIdfLVocBA24gZGmNsi66YTIJeGfN2O1rGOKk/BsxXhnnvDg6XDAH10/kXzNKakDVRGY0DMCiSUwxkozVre0o3wvkwZfWWh6JcomlxDqbCTVLNijIkkoo1GX394wojoe7s8h9HLVHVOD//bACdq9twNc9jvfJJEVk1icygzK6BQxIY81AU6/iKfxUpJ586HGkQjPs+E/Sq5xExo6bpSOa/Ik5u0K19h/P4=
    on:
      condition: $TRAVIS_OS_NAME = "linux"
      tags: true
before_cache:
- rm -rf $HOME/.cache/electron-builder/wine
