osx_image: xcode8.3

dist: trusty
sudo: false

language: node_js
node_js: "8"

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

os:
  - linux
  - osx

cache:
  directories:
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder
  - $HOME/.npm/_prebuilds

addons:
  apt:
    packages:
      - rpm
      - libsecret-1-0
      - libsecret-1-dev
      - libgnome-keyring-dev

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run release-linux; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run release-osx; fi

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

branches:
  only:
  - master
