osx_image: xcode8.3

dist: trusty
sudo: false

language: node_js
node_js: "8"

os:
  - linux
  - osx

notifications:
  email: false

addons:
  apt:
    packages:
      - rpm
      - libsecret-1-0
      - libsecret-1-dev
      - libgnome-keyring-dev

before_script: npm update

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run release-linux; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run release-osx; fi

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine
