osx_image: xcode8.3
dist: trusty
sudo: false
language: node_js
node_js: '8'
os:
- linux
- osx
notifications:
  email: false
addons:
  apt:
    packages:
    - rpm
    - libsecret-1-0
    - libsecret-1-dev
    - libgnome-keyring-dev
before_script: npm update
script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run release-linux; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run release-osx; fi
before_deploy:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      export version=$(cat package.json | grep '"version"' | cut -d '"' -f4);
      if [[ "$TRAVIS_TAG" == *"-"* ]]; then export deb_distribution=unstable; else export deb_distribution=stable; fi;
      if [[ "$TRAVIS_BRANCH" == "master" ]]; then export deb_distribution=nightly; fi;
      export date=$(date +%Y-%m-%d);
      cp packaging/debian/bintray.json bintray.json;
      sed -i s/'{version}'/$version/g bintray.json;
      sed -i s/'{date}'/$date/g bintray.json;
      sed -i s/'{deb_distribution}'/$deb_distribution/g bintray.json;
    fi
deploy:
  - provider: releases
    api_key:
      secure: gcN1ajquIROH2NFCYqF8mksjjCJiczH8PxqALsQQEiZDqq3aCIXJZ3ZE6LjeaBQcmpqE3++EveHC5wmbv2GN3pk8gJ9rPyKc+pjrVbQlwbJv2ioKcQ9JvK7YRn5DCoXBhIh2UN9CK8/ttrQ8Tbc0oArDXvd+KFI7SAoionNqzzc5B/7X/GgN2H3K5KVXtlAsiVlGWgBEZTPKpbnp5KRpGGuERB+FRQg4mru+LT/8PEk/JEZUY5SQYrjwJCB9YFhGh7+vr2Pe6JUyohZBiBGgHDumd5b6jWVb8QmtkxRTm+3WhopZVk8p5TFg50uuhQr7+RNb1xA4ozM5/hEJwmt8nHdh45mkvmrIzeahwnQFQOQl09tzjPPr+zEvqZj5SyIelTnoR9xNzr7r69U40VWyk727NgqXcMHeF5IaskM3fZ3WJbmU4SdALUAPUx9T3tG1nS864mZc41cSNgBkSy8IfYqsXrgUKOyG8BV/usKy9cd+q7Y2x6PsVD5sysT0R7Jfx/dbXUsd1cdMf50Zms8AZ/6tMtI5KxR2n9wAFJNG2E5PSwg8YiG6TXYPkx09TT+H2PGlXqMiSF/uaHYKaUPN1VEa6fR1p+lMTXI2uqutj95P8gSSBJChg6sAqzA/bjrLh7Qjh+URheGJuGhBiksw7ixwAFmFW4ZW+VsKRG0T5Jo=
    file_glob: true
    file: dist/*.deb,dist/*.yml,dist/*.dmg,dist/*.rpm
    skip_cleanup: true
    on:
      master: true
      tags: true
  - provider: bintray
    file: bintray.json
    user: raffis
    key:
      secure: BWv8xZaOQsptR6/CJdvAOD5e7NmEH3aJ83xWfSrxwK52NN7QmSNYBXhM4gMiRvUJXMYIcu6OJhlo3W86M2YOeHGtmH1biLwFp7NxIMEQUouuMBoezg5jU47M4ydk/ro44du/Krvk6jnXHkgHDsnCknPP5RD/Z+Dd2mgTL+iNbvfvklW3pd0y1q1CiZfyaEvRl8OXUyzERnS7NsayjcGOOi5Ea4VYR87tkmXBguV6XQI0CbN9RJ1VQuipYVYevZzMAO1iHDj66nEJYT0XXBOHPUYsYP/iO4bLvXkbUxXi/WU4dQbAkLFD3jYRl3UCpaUvTBoAPooD9Vh8FCq8rUrXfL0TfJ3+awvct7ltKY+E+FiDuiAdlsj+C0uL8n4Do5MNNqE+e22/XrV/Lfhpu7K65173/p6qkJyo1NanqWQJTmmUs1oSVtU+V1Ze6Ybr3BI4J6H/djGkYiIdfLVocBA24gZGmNsi66YTIJeGfN2O1rGOKk/BsxXhnnvDg6XDAH10/kXzNKakDVRGY0DMCiSUwxkozVre0o3wvkwZfWWh6JcomlxDqbCTVLNijIkkoo1GX394wojoe7s8h9HLVHVOD//bACdq9twNc9jvfJJEVk1icygzK6BQxIY81AU6/iKfxUpJ586HGkQjPs+E/Sq5xExo6bpSOa/Ik5u0K19h/P4=
    on:
      condition: ($TRAVIS_OS_NAME = "linux" && $TRAVIS_BRANCH == "master")
  - provider: bintray
    file: bintray.json
    user: raffis
    key:
      secure: BWv8xZaOQsptR6/CJdvAOD5e7NmEH3aJ83xWfSrxwK52NN7QmSNYBXhM4gMiRvUJXMYIcu6OJhlo3W86M2YOeHGtmH1biLwFp7NxIMEQUouuMBoezg5jU47M4ydk/ro44du/Krvk6jnXHkgHDsnCknPP5RD/Z+Dd2mgTL+iNbvfvklW3pd0y1q1CiZfyaEvRl8OXUyzERnS7NsayjcGOOi5Ea4VYR87tkmXBguV6XQI0CbN9RJ1VQuipYVYevZzMAO1iHDj66nEJYT0XXBOHPUYsYP/iO4bLvXkbUxXi/WU4dQbAkLFD3jYRl3UCpaUvTBoAPooD9Vh8FCq8rUrXfL0TfJ3+awvct7ltKY+E+FiDuiAdlsj+C0uL8n4Do5MNNqE+e22/XrV/Lfhpu7K65173/p6qkJyo1NanqWQJTmmUs1oSVtU+V1Ze6Ybr3BI4J6H/djGkYiIdfLVocBA24gZGmNsi66YTIJeGfN2O1rGOKk/BsxXhnnvDg6XDAH10/kXzNKakDVRGY0DMCiSUwxkozVre0o3wvkwZfWWh6JcomlxDqbCTVLNijIkkoo1GX394wojoe7s8h9HLVHVOD//bACdq9twNc9jvfJJEVk1icygzK6BQxIY81AU6/iKfxUpJ586HGkQjPs+E/Sq5xExo6bpSOa/Ik5u0K19h/P4=
    on:
      condition: $TRAVIS_OS_NAME = "linux"
      tags: true
before_cache:
- rm -rf $HOME/.cache/electron-builder/wine
