environment:
  matrix:
    - nodejs_version: '8'

version: "{build}"
build: off
deploy: off
matrix:
  fast_finish: true

cache:

install:
  - ps: Install-Product node $env:nodejs_version x64
  - npm set progress=false
  - npm prune
  - npm install

branches:
  only:
    - master

test_script:
  - node --version
  - npm --version
  - SET PATH=C:\Program Files\Nodejs;%PATH%
  - npm run release-win
