environment:
  matrix:
    - nodejs_version: '8'

version: "{build}"
build: off
matrix:
  fast_finish: true

install:
  - ps: $env:package_version = (Get-Content -Path package.json | ConvertFrom-Json).version
  - ps: Install-Product node $env:nodejs_version x64
  - npm set progress=false
  - npm prune
  - npm install
  - npm run release-win

test_script:
  - node --version
  - npm --version
  - SET PATH=C:\Program Files\Nodejs;%PATH%

artifacts:
  - path: dist/*.exe
    name: exe

  - path: dist/*.yml
    name: latest

  - path: dist/*.zip
    name: zip

deploy:
  release: $(package_version)
  provider: GitHub
  auth_token:
    secure: pUNwihH4K0Qy5dcJ8g3FFkvPyqwOcv5avZYU/JwoY4RVJljy/sq8FuOObDGkZ+Sx
  artifact: exe,latest,zip
  draft: true
  prerelease: false
  force_update: true
  on:
    branch: master
